# Generated by Django 5.2.8 on 2025-12-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='🎭', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория упражнения',
                'verbose_name_plural': 'Категории упражнений',
            },
        ),
        migrations.CreateModel(
            name='PracticalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('instruction', models.TextField(verbose_name='Подробная инструкция')),
                ('text_content', models.TextField(blank=True, verbose_name='Текст для озвучки')),
                ('audio_example', models.FileField(blank=True, null=True, upload_to='exercises/examples/', verbose_name='Пример аудио')),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Сложность')),
                ('estimated_time', models.IntegerField(default=5, verbose_name='Примерное время (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercisecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='exercises/attempts/%Y/%m/%d/', verbose_name='Аудиозапись')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (секунды)')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Оценка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная запись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.practicalexercise', verbose_name='Упражнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка упражнения',
                'verbose_name_plural': 'Попытки упражнений',
                'ordering': ['-created_at'],
            },
        ),
    ]
