# Generated by Django 5.2.8 on 2025-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalexercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-имя'),
        ),
    ]
